all: README.md

readme:
	touch README.md 
	echo "# Guessing Game" > README.md
	echo "* Created on: $$(date +%D) $$(date +"%H:%M")" >> README.md
	echo "* Number of lines of code: $$(cat guessinggame.sh | wc -l) lines in guessinggame.sh" >> README.md

clean:
	rm README.md

	